# Generated by Django 5.0.4 on 2024-06-27 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_censorinfo_movieinfo_censor_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='movieinfo',
            name='dirctedby',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='directed_movie', to='movies.director'),
        ),
    ]
