# Generated by Django 5.0.4 on 2024-07-01 12:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_student_teacher'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('date_of_birth', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.DeleteModel(
            name='Teacher',
        ),
        migrations.CreateModel(
            name='Student1',
            fields=[
                ('person1_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='myapp.person1')),
                ('enrollment_date', models.DateField()),
                ('major', models.CharField(max_length=50)),
            ],
            bases=('myapp.person1',),
        ),
        migrations.CreateModel(
            name='Teacher1',
            fields=[
                ('person1_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='myapp.person1')),
                ('hire_date', models.DateField()),
                ('subject', models.CharField(max_length=50)),
            ],
            bases=('myapp.person1',),
        ),
    ]
