# Generated by Django 5.0.6 on 2024-07-02 06:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='department',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dept_name', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'department',
            },
        ),
        migrations.CreateModel(
            name='studentData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('rollno', models.IntegerField(unique=True)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')])),
                ('place', models.CharField(max_length=150)),
                ('fees_amt', models.IntegerField()),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.department')),
            ],
            options={
                'db_table': 'student_table',
            },
        ),
    ]
